server:
  port: 9443
  ssl:
    bundle: demo-authorizationserver
    client-auth: want

spring:
  application:
    name: AuthServer
  ssl:
    bundle:
      jks:
        demo-authorizationserver:
          key:
            alias: demo-authorizationserver-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          github-idp:
            provider: github
            client-id: Ov23liAd77aaWYtb5wKO
            client-secret: 7d15a6a608d7a99ebf5a6ca59edefcf195dceb18
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          github:
            user-name-attribute: login

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

